# Generated by Django 5.2.7 on 2026-01-29 14:04

import diploma_orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Введите фамилию руководителя', max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(help_text='Введите имя руководителя', max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(help_text='Введите отчество руководителя', max_length=100, verbose_name='Отчество')),
                ('academic_degree', models.CharField(help_text='Например: к.т.н., д.ф.-м.н., PhD', max_length=100, verbose_name='Ученая степень')),
                ('position', models.CharField(help_text='Например: профессор, доцент, старший преподаватель', max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Научный руководитель',
                'verbose_name_plural': 'Научные руководители',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Введите фамилию студента', max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(help_text='Введите имя студента', max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, help_text='Введите отчество студента (необязательно)', max_length=100, null=True, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фотографию студента', null=True, upload_to=diploma_orders.models.student_photo_path, verbose_name='Фотография')),
                ('student_id', models.CharField(help_text='Уникальный идентификатор студента', max_length=20, unique=True, verbose_name='Номер студенческого билета')),
                ('user', models.OneToOneField(blank=True, help_text='Связь с учетной записью пользователя (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DiplomaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Введите полное название темы дипломной работы', max_length=500, verbose_name='Тема дипломной работы')),
                ('registration_date', models.DateField(help_text='Дата утверждения темы дипломной работы', verbose_name='Дата регистрации темы')),
                ('deadline', models.DateField(help_text='Планируемая дата завершения работы', verbose_name='Плановый срок сдачи')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_project', to='diploma_orders.student', verbose_name='Студент')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diploma_projects', to='diploma_orders.supervisor', verbose_name='Научный руководитель')),
            ],
            options={
                'verbose_name': 'Дипломный проект',
                'verbose_name_plural': 'Дипломные проекты',
                'ordering': ['deadline'],
            },
        ),
    ]
