# Generated by Django 5.2.7 on 2026-01-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: ИВТ-401, ПМИ-301', max_length=50, unique=True, verbose_name='Название группы')),
                ('faculty', models.CharField(help_text='Название факультета', max_length=100, verbose_name='Факультет')),
                ('course', models.IntegerField(help_text='Номер курса (1-6)', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.AddField(
            model_name='diplomaproject',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание дипломной работы', null=True, verbose_name='Описание работы'),
        ),
        migrations.AddField(
            model_name='diplomaproject',
            name='status',
            field=models.CharField(choices=[('registered', 'Зарегистрирована'), ('in_progress', 'В работе'), ('review', 'На рецензии'), ('completed', 'Завершена'), ('defended', 'Защищена')], default='registered', max_length=20, verbose_name='Статус работы'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='diploma_orders.group', verbose_name='Учебная группа'),
        ),
    ]
