# Generated by Django 5.2.7 on 2026-01-29 16:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_orders', '0002_group_diplomaproject_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер приказа')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приказа')),
                ('study_form', models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Заочная')], default='full_time', max_length=20, verbose_name='Форма обучения')),
                ('direction', models.CharField(max_length=200, verbose_name='Направление подготовки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Дополнительные примечания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='diploma_orders.group', verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name': 'Приказ по группе',
                'verbose_name_plural': 'Приказы по группам',
                'ordering': ['-order_date'],
            },
        ),
    ]
