# Generated by Django 5.2.7 on 2026-01-31 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_orders', '0003_grouporder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание шаблона')),
                ('template_type', models.CharField(choices=[('student_order', 'Приказ по студенту'), ('group_order', 'Приказ по группе'), ('contract', 'Договор'), ('agreement', 'Соглашение')], default='student_order', max_length=20, verbose_name='Тип шаблона')),
                ('available_fields', models.JSONField(default=list, help_text='Список доступных полей для подстановки в формате JSON', verbose_name='Доступные поля')),
                ('content', models.TextField(help_text='Используйте {{field_name}} для подстановки значений', verbose_name='Содержимое шаблона')),
                ('default_formatting', models.JSONField(blank=True, default=dict, help_text='Настройки форматирования по умолчанию в формате JSON', verbose_name='Настройки форматирования')),
                ('docx_template', models.FileField(blank=True, help_text='Файл .docx с макросом для заполнения', null=True, upload_to='order_templates/', verbose_name='Файл шаблона DOCX')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон приказа',
                'verbose_name_plural': 'Шаблоны приказов',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_data', models.JSONField(default=dict, help_text='Данные, использованные для генерации документа', verbose_name='Данные документа')),
                ('content', models.TextField(verbose_name='Содержимое документа')),
                ('html_file', models.FileField(blank=True, null=True, upload_to='documents/html/', verbose_name='HTML файл')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='documents/docx/', verbose_name='DOCX файл')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/pdf/', verbose_name='PDF файл')),
                ('document_number', models.CharField(max_length=100, unique=True, verbose_name='Номер документа')),
                ('document_date', models.DateField(verbose_name='Дата документа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('generated', 'Сгенерирован'), ('signed', 'Подписан'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='diploma_orders.group', verbose_name='Группа')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='diploma_orders.student', verbose_name='Студент')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='diploma_orders.ordertemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('edit', 'Редактирование'), ('comment', 'Комментарий'), ('approve', 'Согласование'), ('reject', 'Отклонение'), ('sign', 'Подписание'), ('export', 'Экспорт')], max_length=20, verbose_name='Действие')),
                ('changes', models.TextField(blank=True, verbose_name='Изменения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='diploma_orders.generateddocument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'История документа',
                'verbose_name_plural': 'Истории документов',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('content', models.TextField(verbose_name='Содержимое раздела')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('available_fields', models.JSONField(blank=True, default=list, verbose_name='Доступные поля в разделе')),
                ('display_conditions', models.JSONField(blank=True, default=dict, help_text='Условия, при которых раздел отображается', verbose_name='Условия отображения')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный раздел')),
                ('can_be_deleted', models.BooleanField(default=True, verbose_name='Можно удалить')),
                ('can_be_edited', models.BooleanField(default=True, verbose_name='Можно редактировать')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='diploma_orders.ordertemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Раздел шаблона',
                'verbose_name_plural': 'Разделы шаблона',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor', 'Редактор'), ('reviewer', 'Рецензент'), ('approver', 'Согласующий'), ('signatory', 'Подписант'), ('viewer', 'Наблюдатель')], max_length=20, verbose_name='Роль')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Может редактировать')),
                ('can_comment', models.BooleanField(default=False, verbose_name='Может комментировать')),
                ('can_approve', models.BooleanField(default=False, verbose_name='Может согласовывать')),
                ('can_sign', models.BooleanField(default=False, verbose_name='Может подписывать')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный участник')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Присоединился')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='diploma_orders.generateddocument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Участник документа',
                'verbose_name_plural': 'Участники документов',
                'unique_together': {('document', 'user', 'role')},
            },
        ),
    ]
