# Generated by Django 5.2.7 on 2026-02-10 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_orders', '0004_ordertemplate_generateddocument_documenthistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='Подкатегория')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('theory', 'Теоретический'), ('methodology', 'Методологический'), ('practical', 'Практический'), ('analytical', 'Аналитический'), ('critical', 'Критический')], max_length=50, verbose_name='Тип вопроса')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('expert', 'Экспертный')], max_length=20, verbose_name='Сложность')),
                ('tags', models.JSONField(default=list, verbose_name='Теги')),
                ('suggested_answers', models.TextField(blank=True, verbose_name='Примерные ответы')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Использований')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='Успешность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Вопрос ИИ',
                'verbose_name_plural': 'Банк вопросов ИИ',
                'ordering': ['category', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='DiplomaAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_score', models.IntegerField(default=0, verbose_name='Оценка формата')),
                ('format_issues', models.JSONField(default=list, verbose_name='Проблемы формата')),
                ('format_metadata', models.JSONField(default=dict, verbose_name='Метаданные')),
                ('review_text', models.TextField(blank=True, verbose_name='Текст рецензии')),
                ('review_grade', models.CharField(blank=True, max_length=50, verbose_name='Оценка')),
                ('review_generated_at', models.DateTimeField(null=True, verbose_name='Дата рецензии')),
                ('questions', models.JSONField(default=list, verbose_name='Вопросы для защиты')),
                ('content_analysis', models.JSONField(default=dict, verbose_name='Анализ содержания')),
                ('ai_provider', models.CharField(default='openai', max_length=50, verbose_name='Провайдер ИИ')),
                ('raw_response', models.JSONField(default=dict, verbose_name='Сырой ответ ИИ')),
                ('file_metadata', models.JSONField(default=dict, verbose_name='Метаданные файла')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('diploma_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='diploma_orders.diplomaproject', verbose_name='Дипломный проект')),
            ],
            options={
                'verbose_name': 'Анализ ИИ диплома',
                'verbose_name_plural': 'Анализы ИИ дипломов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageAIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500, verbose_name='URL страницы')),
                ('page_title', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('page_context', models.TextField(blank=True, verbose_name='Контекст страницы')),
                ('page_summary', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('questions_asked', models.JSONField(default=list, verbose_name='Заданные вопросы')),
                ('ai_responses', models.JSONField(default=list, verbose_name='Ответы ИИ')),
                ('session_id', models.CharField(max_length=100, verbose_name='ID сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_interaction', models.DateTimeField(auto_now=True, verbose_name='Последнее взаимодействие')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взаимодействие с ИИ',
                'verbose_name_plural': 'Взаимодействия с ИИ',
                'ordering': ['-last_interaction'],
            },
        ),
    ]
