# Generated by Django 5.2.7 on 2026-02-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_orders', '0005_aiquestionbank_diplomaaianalysis_pageaiinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomaproject',
            name='file',
            field=models.FileField(blank=True, help_text='Загрузите файл дипломной работы (PDF, DOCX, DOC, TXT)', null=True, upload_to='diplomas/%Y/%m/%d/', verbose_name='Файл диплома'),
        ),
    ]
